### ISSUE TITLE
ExceptionInInitializerError in Keycloak: error found in ResourceLoader

### ISSUE THREAD

**Issue by MoreDreadd** [nulab/zxcvbn4j#79]
Hi team,

I wanted to use this library to create a Keycloak extension checking for the strength of the password.
But everytime I tried calling the `zxcvbn.measure()` method, I got a `java.lang.ExceptionInInitializerError`.

```
Uncaught server error: java.lang.ExceptionInInitializerError
	at deployment.keycloak-extensions-bundle-11.0.0-SNAPSHOT.ear.keycloak-keycloak-extensions-password-strength-11.0.0-SNAPSHOT.jar//com.nulabinc.zxcvbn.Matching.<clinit>(Matching.java:18)
	at deployment.keycloak-extensions-bundle-11.0.0-SNAPSHOT.ear.keycloak-keycloak-extensions-password-strength-11.0.0-SNAPSHOT.jar//com.nulabinc.zxcvbn.Zxcvbn.createMatching(Zxcvbn.java:45)
	at deployment.keycloak-extensions-bundle-11.0.0-SNAPSHOT.ear.keycloak-keycloak-extensions-password-strength-11.0.0-SNAPSHOT.jar//com.nulabinc.zxcvbn.Zxcvbn.measure(Zxcvbn.java:32)
	at deployment.keycloak-extensions-bundle-11.0.0-SNAPSHOT.ear.keycloak-keycloak-extensions-password-strength-11.0.0-SNAPSHOT.jar//com.nulabinc.zxcvbn.Zxcvbn.measure(Zxcvbn.java:15)
	at deployment.keycloak-extensions-bundle-11.0.0-SNAPSHOT.ear.keycloak-keycloak-extensions-password-strength-11.0.0-SNAPSHOT.jar//keycloak.passwordstrength.PasswordStrengthProvider.validate(PasswordStrengthProvider.java:31)
	at deployment.keycloak-extensions-bundle-11.0.0-SNAPSHOT.ear.keycloak-keycloak-extensions-password-strength-11.0.0-SNAPSHOT.jar//keycloak.passwordstrength.PasswordStrengthProvider.validate(PasswordStrengthProvider.java:26)

[...]

Caused by: java.lang.NullPointerException
	at java.base/java.io.Reader.<init>(Reader.java:167)
	at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:109)
	at deployment.keycloak-extensions-bundle-11.0.0-SNAPSHOT.ear.keycloak-keycloak-extensions-password-strength-11.0.0-SNAPSHOT.jar//com.nulabinc.zxcvbn.matchers.Dictionary.read(Dictionary.java:40)
	at deployment.keycloak-extensions-bundle-11.0.0-SNAPSHOT.ear.keycloak-keycloak-extensions-password-strength-11.0.0-SNAPSHOT.jar//com.nulabinc.zxcvbn.matchers.Dictionary.<clinit>(Dictionary.java:25)
        ... 105 more
```

After debugging for hours I was able to locate the error: in `matchers/ResourceLoader.java` in [line 8](https://github.com/nulab/zxcvbn4j/blob/9dcdf7348be9d8837c19059abef96d52367f6363/src/main/java/com/nulabinc/zxcvbn/matchers/ResourceLoader.java#L8), you are using `Thread.currentThread().getContextClassLoader().getResourceAsStream(path)` to get the files from the resources folder. As it turned out, this is `null` when using Keycloak.
But: using `getClass ().getClassLoader ().getResourceAsStream (path)` works great!

Is there a reason you are using the Thread-version here? Otherwise it might be nice to replace this line with the Class-version to ensure compatibility with software like Keycloak (I don't know if this problem also appears with other projects).

**Comment by vvatanabe** [comment]
@MoreDreadd 
We are currently investigating. There was a similar bug report below.
https://github.com/nulab/zxcvbn4j/issues/66

Are you also using Android with zxcvbn4j?

**Comment by MoreDreadd** [comment]
@vvatanabe no, I am running the program on Windows 10

**Comment by vvatanabe** [comment]
@MoreDreadd 
In matchers/ResourceLoader.java on line 8, the result of Thread.currentThread().getContextClassLoader().getResourceAsStream(path) is null, right?

In this case, ClassLoader.getSystemResourceAsStream(path) in the 12th line is executed, is it also null?

**Comment by vvatanabe** [comment]
@MoreDreadd  I fixed it and released 1.3.2. Please check it!

**Comment by MoreDreadd** [comment]
@vvatanabe I just checked and unfortunately it still doesn't work.
I have to correct my report from above: not the result of `Thread.currentThread().getContextClassLoader().getResourceAsStream(path)` is `null`, but the result of `RESOURCE_LOADER.getInputStream(buildResourcePath(filename))` in [line 45 in Dictionary](https://github.com/nulab/zxcvbn4j/blob/cbc5ec62a7b1fcc7b7006aaee603e7018a443ad9/src/main/java/com/nulabinc/zxcvbn/matchers/Dictionary.java#L45) which is why the fallback cases don't work.

**Comment by vvatanabe** [comment]
@MoreDreadd
Thanks for reporting. We will continue to investigate. Could you please provide the following information?
- OS details
- Java version
- Are you running it on WSL or Docker for Windows?
- Stack trace when an error occurs

**Comment by vvatanabe** [comment]
@MoreDreadd I released 1.3.3 include #81. Please check it!
